name: fp_tekber_8
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.4
  intl: ^0.20.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0 
  image_picker: ^0.8.7+4
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4 # Tambahkan ini jika menggunakan Authentication
  cloud_firestore: ^5.5.0 # Tambahkan jika menggunakan Firestore
  firebase_storage: ^12.3.7 # Tambahkan jika menggunakan Storage
  pdf: ^3.11.1
  path_provider: ^2.0.11
  permission_handler: ^10.3.0
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.4.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gradasi.jpg
    - assets/header.jpg
    - assets/bismillah.png
    - assets/gula.jpg
    - assets/ayam.jpg
    - assets/minyak.jpg
    - assets/susu.jpg
    - assets/beras.jpg
    - assets/logotekber.png
    - assets/dompet.png
    - assets/confirmation_image.png

