// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9_jJqr7CM18lVyNg4OaL5BaRWbIF8VSk',
    appId: '1:960057824489:web:999b269ba3f2292036cc78',
    messagingSenderId: '960057824489',
    projectId: 'fp-tekber-8',
    authDomain: 'fp-tekber-8.firebaseapp.com',
    storageBucket: 'fp-tekber-8.firebasestorage.app',
    measurementId: 'G-SQP3HZMV35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvRS5Zutb88lYzprNDxTKhhZI9w9UfP-Y',
    appId: '1:960057824489:android:71c2a653f6dd825f36cc78',
    messagingSenderId: '960057824489',
    projectId: 'fp-tekber-8',
    storageBucket: 'fp-tekber-8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPPmI9d2GqCTwVAo4dI1qa2foVtk8th2g',
    appId: '1:960057824489:ios:73367751f105831136cc78',
    messagingSenderId: '960057824489',
    projectId: 'fp-tekber-8',
    storageBucket: 'fp-tekber-8.firebasestorage.app',
    iosBundleId: 'com.example.fpTekber8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPPmI9d2GqCTwVAo4dI1qa2foVtk8th2g',
    appId: '1:960057824489:ios:73367751f105831136cc78',
    messagingSenderId: '960057824489',
    projectId: 'fp-tekber-8',
    storageBucket: 'fp-tekber-8.firebasestorage.app',
    iosBundleId: 'com.example.fpTekber8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9_jJqr7CM18lVyNg4OaL5BaRWbIF8VSk',
    appId: '1:960057824489:web:6eadb5082dc29c3236cc78',
    messagingSenderId: '960057824489',
    projectId: 'fp-tekber-8',
    authDomain: 'fp-tekber-8.firebaseapp.com',
    storageBucket: 'fp-tekber-8.firebasestorage.app',
    measurementId: 'G-0DNN7HQFMK',
  );
}
